version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask-project
    restart: always
    expose:
      - 8080
    volumes:
      - ./flask:/app

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
