version: "3.7"

services:

  microservices:
    build:
      context: ./
    container_name: microservices
    env_file:
      - dev.env
    restart: always
    volumes:
      - "./app:/usr/src/app:rw"
    ports:
      - "80:80"
